/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountLockedOutException
 */
export interface AccountLockedOutException {
    /**
     * 
     * @type {string}
     * @memberof AccountLockedOutException
     */
    name?: AccountLockedOutExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountLockedOutException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum AccountLockedOutExceptionNameEnum {
    AccountLockedOutException = 'account_locked_out_exception'
}

export function AccountLockedOutExceptionFromJSON(json: any): AccountLockedOutException {
    return AccountLockedOutExceptionFromJSONTyped(json, false);
}

export function AccountLockedOutExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLockedOutException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AccountLockedOutExceptionToJSON(value?: AccountLockedOutException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

