/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountEmail
 */
export interface AccountEmail {
    /**
     * 
     * @type {number}
     * @memberof AccountEmail
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountEmail
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountEmail
     */
    primaryEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccountEmail
     */
    mailForwarding?: boolean;
}

export function AccountEmailFromJSON(json: any): AccountEmail {
    return AccountEmailFromJSONTyped(json, false);
}

export function AccountEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'primaryEmail': !exists(json, 'primary_email') ? undefined : json['primary_email'],
        'mailForwarding': !exists(json, 'mail_forwarding') ? undefined : json['mail_forwarding'],
    };
}

export function AccountEmailToJSON(value?: AccountEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'primary_email': value.primaryEmail,
        'mail_forwarding': value.mailForwarding,
    };
}

