/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlreadyForwardedException
 */
export interface AlreadyForwardedException {
    /**
     * 
     * @type {string}
     * @memberof AlreadyForwardedException
     */
    name?: AlreadyForwardedExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof AlreadyForwardedException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum AlreadyForwardedExceptionNameEnum {
    AlreadyForwardedException = 'already_forwarded_exception'
}

export function AlreadyForwardedExceptionFromJSON(json: any): AlreadyForwardedException {
    return AlreadyForwardedExceptionFromJSONTyped(json, false);
}

export function AlreadyForwardedExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlreadyForwardedException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AlreadyForwardedExceptionToJSON(value?: AlreadyForwardedException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

