/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlreadyInvitedException
 */
export interface AlreadyInvitedException {
    /**
     * 
     * @type {string}
     * @memberof AlreadyInvitedException
     */
    name?: AlreadyInvitedExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof AlreadyInvitedException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum AlreadyInvitedExceptionNameEnum {
    AlreadyInvitedException = 'already_invited_exception'
}

export function AlreadyInvitedExceptionFromJSON(json: any): AlreadyInvitedException {
    return AlreadyInvitedExceptionFromJSONTyped(json, false);
}

export function AlreadyInvitedExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlreadyInvitedException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AlreadyInvitedExceptionToJSON(value?: AlreadyInvitedException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

