/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AlterEgoBlockedDomainAllOf,
    AlterEgoBlockedDomainAllOfFromJSON,
    AlterEgoBlockedDomainAllOfFromJSONTyped,
    AlterEgoBlockedDomainAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface AlterEgoBlockedDomain
 */
export interface AlterEgoBlockedDomain {
    /**
     * 
     * @type {number}
     * @memberof AlterEgoBlockedDomain
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof AlterEgoBlockedDomain
     */
    domain?: string;
    /**
     * 
     * @type {Date}
     * @memberof AlterEgoBlockedDomain
     */
    readonly blockedAt?: Date;
}

export function AlterEgoBlockedDomainFromJSON(json: any): AlterEgoBlockedDomain {
    return AlterEgoBlockedDomainFromJSONTyped(json, false);
}

export function AlterEgoBlockedDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterEgoBlockedDomain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'blockedAt': !exists(json, 'blocked_at') ? undefined : (new Date(json['blocked_at'])),
    };
}

export function AlterEgoBlockedDomainToJSON(value?: AlterEgoBlockedDomain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domain': value.domain,
    };
}

