/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AlterEgoMailStatusAllOf,
    AlterEgoMailStatusAllOfFromJSON,
    AlterEgoMailStatusAllOfFromJSONTyped,
    AlterEgoMailStatusAllOfToJSON,
    ForwardEmailResult,
    ForwardEmailResultFromJSON,
    ForwardEmailResultFromJSONTyped,
    ForwardEmailResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface AlterEgoMailStatus
 */
export interface AlterEgoMailStatus {
    /**
     * 
     * @type {number}
     * @memberof AlterEgoMailStatus
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof AlterEgoMailStatus
     */
    readonly sender?: string;
    /**
     * 
     * @type {string}
     * @memberof AlterEgoMailStatus
     */
    readonly from?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlterEgoMailStatus
     */
    readonly fromAddress?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AlterEgoMailStatus
     */
    readonly subject?: string;
    /**
     * 
     * @type {Date}
     * @memberof AlterEgoMailStatus
     */
    readonly receivedAt?: Date;
    /**
     * 
     * @type {Array<ForwardEmailResult>}
     * @memberof AlterEgoMailStatus
     */
    readonly forwardEmailResults?: Array<ForwardEmailResult>;
}

export function AlterEgoMailStatusFromJSON(json: any): AlterEgoMailStatus {
    return AlterEgoMailStatusFromJSONTyped(json, false);
}

export function AlterEgoMailStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterEgoMailStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'sender': !exists(json, 'sender') ? undefined : json['sender'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'fromAddress': !exists(json, 'from_address') ? undefined : json['from_address'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'receivedAt': !exists(json, 'received_at') ? undefined : (new Date(json['received_at'])),
        'forwardEmailResults': !exists(json, 'forward_email_results') ? undefined : ((json['forward_email_results'] as Array<any>).map(ForwardEmailResultFromJSON)),
    };
}

export function AlterEgoMailStatusToJSON(value?: AlterEgoMailStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

