/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreditCard,
    CreditCardFromJSON,
    CreditCardFromJSONTyped,
    CreditCardToJSON,
    Email,
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
    SMS,
    SMSFromJSON,
    SMSFromJSONTyped,
    SMSToJSON,
} from './';

/**
 * 
 * @export
 * @interface AlterEgoAllOf
 */
export interface AlterEgoAllOf {
    /**
     * 
     * @type {number}
     * @memberof AlterEgoAllOf
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof AlterEgoAllOf
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof AlterEgoAllOf
     */
    emailIds?: Array<number>;
    /**
     * 
     * @type {Email}
     * @memberof AlterEgoAllOf
     */
    readonly email?: Email;
    /**
     * 
     * @type {boolean}
     * @memberof AlterEgoAllOf
     */
    emailActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AlterEgoAllOf
     */
    smsId?: number;
    /**
     * 
     * @type {SMS}
     * @memberof AlterEgoAllOf
     */
    readonly sms?: SMS;
    /**
     * 
     * @type {number}
     * @memberof AlterEgoAllOf
     */
    creditCardId?: number;
    /**
     * 
     * @type {CreditCard}
     * @memberof AlterEgoAllOf
     */
    readonly creditCard?: CreditCard;
    /**
     * 
     * @type {Date}
     * @memberof AlterEgoAllOf
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AlterEgoAllOf
     */
    readonly updatedAt?: Date;
}

export function AlterEgoAllOfFromJSON(json: any): AlterEgoAllOf {
    return AlterEgoAllOfFromJSONTyped(json, false);
}

export function AlterEgoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlterEgoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'emailIds': !exists(json, 'email_ids') ? undefined : json['email_ids'],
        'email': !exists(json, 'email') ? undefined : EmailFromJSON(json['email']),
        'emailActive': !exists(json, 'email_active') ? undefined : json['email_active'],
        'smsId': !exists(json, 'sms_id') ? undefined : json['sms_id'],
        'sms': !exists(json, 'sms') ? undefined : SMSFromJSON(json['sms']),
        'creditCardId': !exists(json, 'credit_card_id') ? undefined : json['credit_card_id'],
        'creditCard': !exists(json, 'credit_card') ? undefined : CreditCardFromJSON(json['credit_card']),
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function AlterEgoAllOfToJSON(value?: AlterEgoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email_ids': value.emailIds,
        'email_active': value.emailActive,
        'sms_id': value.smsId,
        'credit_card_id': value.creditCardId,
    };
}

