/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockedInfo
 */
export interface BlockedInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof BlockedInfo
     */
    readonly domains?: Array<string>;
}

export function BlockedInfoFromJSON(json: any): BlockedInfo {
    return BlockedInfoFromJSONTyped(json, false);
}

export function BlockedInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockedInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domains': !exists(json, 'domains') ? undefined : json['domains'],
    };
}

export function BlockedInfoToJSON(value?: BlockedInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

