/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmRegistration
 */
export interface ConfirmRegistration {
    /**
     * 
     * @type {string}
     * @memberof ConfirmRegistration
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmRegistration
     */
    code: string;
}

export function ConfirmRegistrationFromJSON(json: any): ConfirmRegistration {
    return ConfirmRegistrationFromJSONTyped(json, false);
}

export function ConfirmRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function ConfirmRegistrationToJSON(value?: ConfirmRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'code': value.code,
    };
}

