/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreditCardAllOf,
    CreditCardAllOfFromJSON,
    CreditCardAllOfFromJSONTyped,
    CreditCardAllOfToJSON,
    Id,
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreditCard
 */
export interface CreditCard {
    /**
     * 
     * @type {number}
     * @memberof CreditCard
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    cardNumber: string;
}

export function CreditCardFromJSON(json: any): CreditCard {
    return CreditCardFromJSONTyped(json, false);
}

export function CreditCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cardNumber': json['card_number'],
    };
}

export function CreditCardToJSON(value?: CreditCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_number': value.cardNumber,
    };
}

