/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecryptedEmail
 */
export interface DecryptedEmail {
    /**
     * Decrypted email address
     * @type {string}
     * @memberof DecryptedEmail
     */
    readonly email: string;
}

export function DecryptedEmailFromJSON(json: any): DecryptedEmail {
    return DecryptedEmailFromJSONTyped(json, false);
}

export function DecryptedEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptedEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function DecryptedEmailToJSON(value?: DecryptedEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

