/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAlreadyConfirmedException
 */
export interface EmailAlreadyConfirmedException {
    /**
     * 
     * @type {string}
     * @memberof EmailAlreadyConfirmedException
     */
    name?: EmailAlreadyConfirmedExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailAlreadyConfirmedException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum EmailAlreadyConfirmedExceptionNameEnum {
    EmailAlreadyConfirmedException = 'email_already_confirmed_exception'
}

export function EmailAlreadyConfirmedExceptionFromJSON(json: any): EmailAlreadyConfirmedException {
    return EmailAlreadyConfirmedExceptionFromJSONTyped(json, false);
}

export function EmailAlreadyConfirmedExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAlreadyConfirmedException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function EmailAlreadyConfirmedExceptionToJSON(value?: EmailAlreadyConfirmedException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

