/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ForwardEmail,
    ForwardEmailFromJSON,
    ForwardEmailFromJSONTyped,
    ForwardEmailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmailAllOf
 */
export interface EmailAllOf {
    /**
     * 
     * @type {string}
     * @memberof EmailAllOf
     */
    alterEgoEmail: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmailAllOf
     */
    allDomainBlocked?: boolean;
    /**
     * 
     * @type {Array<ForwardEmail>}
     * @memberof EmailAllOf
     */
    forwardEmails: Array<ForwardEmail>;
}

export function EmailAllOfFromJSON(json: any): EmailAllOf {
    return EmailAllOfFromJSONTyped(json, false);
}

export function EmailAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alterEgoEmail': json['alter_ego_email'],
        'allDomainBlocked': !exists(json, 'all_domain_blocked') ? undefined : json['all_domain_blocked'],
        'forwardEmails': ((json['forward_emails'] as Array<any>).map(ForwardEmailFromJSON)),
    };
}

export function EmailAllOfToJSON(value?: EmailAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alter_ego_email': value.alterEgoEmail,
        'all_domain_blocked': value.allDomainBlocked,
        'forward_emails': ((value.forwardEmails as Array<any>).map(ForwardEmailToJSON)),
    };
}

