/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailNotFoundException
 */
export interface EmailNotFoundException {
    /**
     * 
     * @type {string}
     * @memberof EmailNotFoundException
     */
    name?: EmailNotFoundExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailNotFoundException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum EmailNotFoundExceptionNameEnum {
    EmailNotFoundException = 'email_not_found_exception'
}

export function EmailNotFoundExceptionFromJSON(json: any): EmailNotFoundException {
    return EmailNotFoundExceptionFromJSONTyped(json, false);
}

export function EmailNotFoundExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotFoundException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function EmailNotFoundExceptionToJSON(value?: EmailNotFoundException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

