/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncryptedEmail
 */
export interface EncryptedEmail {
    /**
     * Encrypted email address
     * @type {string}
     * @memberof EncryptedEmail
     */
    email: string;
}

export function EncryptedEmailFromJSON(json: any): EncryptedEmail {
    return EncryptedEmailFromJSONTyped(json, false);
}

export function EncryptedEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncryptedEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EncryptedEmailToJSON(value?: EncryptedEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

