/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForwardEmailAllOf
 */
export interface ForwardEmailAllOf {
    /**
     * 
     * @type {string}
     * @memberof ForwardEmailAllOf
     */
    email: string;
}

export function ForwardEmailAllOfFromJSON(json: any): ForwardEmailAllOf {
    return ForwardEmailAllOfFromJSONTyped(json, false);
}

export function ForwardEmailAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForwardEmailAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ForwardEmailAllOfToJSON(value?: ForwardEmailAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

