/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ForwardEmailResultAllOf,
    ForwardEmailResultAllOfFromJSON,
    ForwardEmailResultAllOfFromJSONTyped,
    ForwardEmailResultAllOfToJSON,
    ResultDetail,
    ResultDetailFromJSON,
    ResultDetailFromJSONTyped,
    ResultDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface ForwardEmailResult
 */
export interface ForwardEmailResult {
    /**
     * 
     * @type {number}
     * @memberof ForwardEmailResult
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ForwardEmailResult
     */
    readonly resultType?: ForwardEmailResultResultTypeEnum;
    /**
     * 
     * @type {ResultDetail}
     * @memberof ForwardEmailResult
     */
    resultDetails?: ResultDetail;
    /**
     * 
     * @type {Date}
     * @memberof ForwardEmailResult
     */
    readonly processedAt?: Date;
}

/**
* @export
* @enum {string}
*/
export enum ForwardEmailResultResultTypeEnum {
    Forwarded = 'forwarded',
    AllDomainIsBlocked = 'all_domain_is_blocked',
    BlockedByDomain = 'blocked_by_domain',
    AlterEgoEmailIsDisabled = 'alter_ego_email_is_disabled',
    AlterEgoIsDeleted = 'alter_ego_is_deleted',
    UserIsDeleted = 'user_is_deleted'
}

export function ForwardEmailResultFromJSON(json: any): ForwardEmailResult {
    return ForwardEmailResultFromJSONTyped(json, false);
}

export function ForwardEmailResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForwardEmailResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'resultType': !exists(json, 'result_type') ? undefined : json['result_type'],
        'resultDetails': !exists(json, 'result_details') ? undefined : ResultDetailFromJSON(json['result_details']),
        'processedAt': !exists(json, 'processed_at') ? undefined : (new Date(json['processed_at'])),
    };
}

export function ForwardEmailResultToJSON(value?: ForwardEmailResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result_details': ResultDetailToJSON(value.resultDetails),
    };
}

