/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationReachedMaxCountException
 */
export interface InvitationReachedMaxCountException {
    /**
     * 
     * @type {string}
     * @memberof InvitationReachedMaxCountException
     */
    name?: InvitationReachedMaxCountExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof InvitationReachedMaxCountException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum InvitationReachedMaxCountExceptionNameEnum {
    InvitationReachedMaxCountException = 'invitation_reached_max_count_exception'
}

export function InvitationReachedMaxCountExceptionFromJSON(json: any): InvitationReachedMaxCountException {
    return InvitationReachedMaxCountExceptionFromJSONTyped(json, false);
}

export function InvitationReachedMaxCountExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationReachedMaxCountException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InvitationReachedMaxCountExceptionToJSON(value?: InvitationReachedMaxCountException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

