/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationAllOf
 */
export interface InvitationAllOf {
    /**
     * 
     * @type {number}
     * @memberof InvitationAllOf
     */
    readonly id?: number;
    /**
     * The email address who you want to invite
     * @type {string}
     * @memberof InvitationAllOf
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof InvitationAllOf
     */
    readonly invitedAt?: Date;
}

export function InvitationAllOfFromJSON(json: any): InvitationAllOf {
    return InvitationAllOfFromJSONTyped(json, false);
}

export function InvitationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'invitedAt': !exists(json, 'invited_at') ? undefined : (new Date(json['invited_at'])),
    };
}

export function InvitationAllOfToJSON(value?: InvitationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

