/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteAlterEgoEmailException
 */
export interface InviteAlterEgoEmailException {
    /**
     * 
     * @type {string}
     * @memberof InviteAlterEgoEmailException
     */
    name?: InviteAlterEgoEmailExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof InviteAlterEgoEmailException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum InviteAlterEgoEmailExceptionNameEnum {
    InviteAlterEgoEmailException = 'invite_alter_ego_email_exception'
}

export function InviteAlterEgoEmailExceptionFromJSON(json: any): InviteAlterEgoEmailException {
    return InviteAlterEgoEmailExceptionFromJSONTyped(json, false);
}

export function InviteAlterEgoEmailExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteAlterEgoEmailException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InviteAlterEgoEmailExceptionToJSON(value?: InviteAlterEgoEmailException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

