/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountEmail,
    AccountEmailFromJSON,
    AccountEmailFromJSONTyped,
    AccountEmailToJSON,
    OptOutStatus,
    OptOutStatusFromJSON,
    OptOutStatusFromJSONTyped,
    OptOutStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface Me
 */
export interface Me {
    /**
     * 
     * @type {Array<AccountEmail>}
     * @memberof Me
     */
    accountEmails: Array<AccountEmail>;
    /**
     * 
     * @type {OptOutStatus}
     * @memberof Me
     */
    optOutStatus: OptOutStatus;
    /**
     * 
     * @type {boolean}
     * @memberof Me
     */
    invited: boolean;
}

export function MeFromJSON(json: any): Me {
    return MeFromJSONTyped(json, false);
}

export function MeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountEmails': ((json['account_emails'] as Array<any>).map(AccountEmailFromJSON)),
        'optOutStatus': OptOutStatusFromJSON(json['opt_out_status']),
        'invited': json['invited'],
    };
}

export function MeToJSON(value?: Me | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_emails': ((value.accountEmails as Array<any>).map(AccountEmailToJSON)),
        'opt_out_status': OptOutStatusToJSON(value.optOutStatus),
        'invited': value.invited,
    };
}

