/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestDeleteEmail
 */
export interface RequestDeleteEmail {
    /**
     * 
     * @type {number}
     * @memberof RequestDeleteEmail
     */
    accountMailAddressId: number;
}

export function RequestDeleteEmailFromJSON(json: any): RequestDeleteEmail {
    return RequestDeleteEmailFromJSONTyped(json, false);
}

export function RequestDeleteEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestDeleteEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountMailAddressId': json['account_mail_address_id'],
    };
}

export function RequestDeleteEmailToJSON(value?: RequestDeleteEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_mail_address_id': value.accountMailAddressId,
    };
}

