/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestChangeEmail
 */
export interface RequestChangeEmail {
    /**
     * 
     * @type {string}
     * @memberof RequestChangeEmail
     */
    email: string;
}

export function RequestChangeEmailFromJSON(json: any): RequestChangeEmail {
    return RequestChangeEmailFromJSONTyped(json, false);
}

export function RequestChangeEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestChangeEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestChangeEmailToJSON(value?: RequestChangeEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

