/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockedInfo,
    BlockedInfoFromJSON,
    BlockedInfoFromJSONTyped,
    BlockedInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResultDetail
 */
export interface ResultDetail {
    /**
     * 
     * @type {Array<string>}
     * @memberof ResultDetail
     */
    readonly domains?: Array<string>;
}

export function ResultDetailFromJSON(json: any): ResultDetail {
    return ResultDetailFromJSONTyped(json, false);
}

export function ResultDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domains': !exists(json, 'domains') ? undefined : json['domains'],
    };
}

export function ResultDetailToJSON(value?: ResultDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

