/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelfInvitationException
 */
export interface SelfInvitationException {
    /**
     * 
     * @type {string}
     * @memberof SelfInvitationException
     */
    name?: SelfInvitationExceptionNameEnum;
    /**
     * 
     * @type {string}
     * @memberof SelfInvitationException
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum SelfInvitationExceptionNameEnum {
    SelfInvitationException = 'self_invitation_exception'
}

export function SelfInvitationExceptionFromJSON(json: any): SelfInvitationException {
    return SelfInvitationExceptionFromJSONTyped(json, false);
}

export function SelfInvitationExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelfInvitationException {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function SelfInvitationExceptionToJSON(value?: SelfInvitationException | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

