/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Id,
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
    SMSAllOf,
    SMSAllOfFromJSON,
    SMSAllOfFromJSONTyped,
    SMSAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface SMS
 */
export interface SMS {
    /**
     * 
     * @type {number}
     * @memberof SMS
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SMS
     */
    phoneNumber: string;
}

export function SMSFromJSON(json: any): SMS {
    return SMSFromJSONTyped(json, false);
}

export function SMSFromJSONTyped(json: any, ignoreDiscriminator: boolean): SMS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'phoneNumber': json['phone_number'],
    };
}

export function SMSToJSON(value?: SMS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone_number': value.phoneNumber,
    };
}

