/* tslint:disable */
/* eslint-disable */
/**
 * bunsin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedError
 */
export interface UnauthorizedError {
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedError
     */
    name?: UnauthorizedErrorNameEnum;
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedError
     */
    message?: string;
}

/**
* @export
* @enum {string}
*/
export enum UnauthorizedErrorNameEnum {
    UnauthorizedError = 'unauthorized_error'
}

export function UnauthorizedErrorFromJSON(json: any): UnauthorizedError {
    return UnauthorizedErrorFromJSONTyped(json, false);
}

export function UnauthorizedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function UnauthorizedErrorToJSON(value?: UnauthorizedError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'message': value.message,
    };
}

